pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: jenkins-kaniko
spec:
  serviceAccountName: jenkins-sa
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.16.0-debug
      imagePullPolicy: Always
      command:
        - sleep
      args:
        - 99d
    - name: git
      image: alpine/git:2.43.0
      imagePullPolicy: Always
      command:
        - sh
      args:
        - -c
        - sleep 99d
"""
    }
  }

  environment {
    ECR_REPO_URL = "961906078703.dkr.ecr.eu-west-1.amazonaws.com/final-project-django-ecr"
    IMAGE_TAG    = "${BUILD_NUMBER}"
    CHART_REPO_URL = "https://github.com/Lichknyaz/DevOps.git"
    CHART_PATH   = "final-project/charts/django-app"
    CHART_VALUES = "values.yaml"
    COMMIT_EMAIL = "jenkins@example.local"
    COMMIT_NAME  = "jenkins"
  }

  stages {
    stage('Build & Push Docker Image') {
      steps {
        container('kaniko') {
          sh '''
            /kaniko/executor \\
              --context `pwd`/final-project/Django \\
              --dockerfile `pwd`/final-project/Django/Dockerfile \\
              --destination=$ECR_REPO_URL:$IMAGE_TAG \\
              --cache=true \\
              --insecure \\
              --skip-tls-verify
          '''
        }
      }
    }

    stage('Update Chart Tag in Git') {
      steps {
        container('git') {
          withCredentials([usernamePassword(credentialsId: 'github-token', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_TOKEN')]) {
            sh '''
              set -e
              rm -rf chart-repo
              git clone https://$GIT_USER:$GIT_TOKEN@${CHART_REPO_URL#https://} chart-repo
              cd chart-repo/$CHART_PATH
              sed -i "s/^  tag: .*/  tag: \\"$IMAGE_TAG\\"/" $CHART_VALUES
              git config user.email "$COMMIT_EMAIL"
              git config user.name "$COMMIT_NAME"
              git add $CHART_VALUES
              git commit -m "Update image tag to $IMAGE_TAG"
              git push origin final-project
            '''
          }
        }
      }
    }
  }
}
