applications:
  - name: example-app
    namespace: default
    project: default
    source:
      repoURL: https://github.com/Lichknyaz/example-repo.git
      path: charts/django-app
      targetRevision: main
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

repositories:
  - name: example-app
    url: https://github.com/Lichknyaz/example-repo.git
    username: Lichknyaz
    password: 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

repoConfig:
  insecure: "true"
  enableLfs: "true"
